binary_gap:
  n_regressors:
  - 10
  - 20
  - 30
  neural_network:
    lr:
    - 0.001
    - 0.005
    - 0.01
    n_hidden_units:
    - 256
    - 1024
    - 2048
    n_layers:
    - 1
    - 2
    - 3
data:
  geo_extrapolation: true
  gt:
    summarypath: /data/eop/country_data/togo/cleaned/cdr_and_survey/summary.parquet
    trainpath: /data/eop/country_data/togo/cleaned/cdr_and_survey/train.parquet
  outcome: consumption_per_capita_per_day
  weight: headcount_adjusted_hh_wgt
device: cuda
savedir: /home/selker/eop/eop/run_togo_simulations/simulations/hparam/results/togo_cdr_and_survey
