data:
  geo_extrapolation: true
  gt:
    summarypath: /data/eop/country_data/togo/cleaned/cdr/summary.parquet
    trainpath: /data/eop/country_data/togo/cleaned/cdr/train.parquet
  outcome: consumption_per_capita_per_day
  weight: headcount_adjusted_hh_wgt
device: cuda
modern_pmt:
  neural_network:
    lr:
    - 0.001
    - 0.005
    - 0.01
    n_hidden_units:
    - 256
    - 1024
    - 2048
    n_layers:
    - 1
    - 2
    - 3
savedir: /home/selker/eop/eop/run_togo_simulations/simulations/hparam/results/togo_cdr
