data:
  geo_extrapolation: true
  outcome: consumption_per_capita_per_day
  weight: headcount_adjusted_hh_wgt
savedir: /home/selker/eop/eop/run_togo_simulations/simulations/learn/results/togo_satellite_and_survey
ubi: {}
