data:
  geo_extrapolation: true
  outcome: consumption_per_capita_per_day
  weight: headcount_adjusted_hh_wgt
oracle_gap: {}
savedir: /home/selker/eop/eop/run_togo_simulations/simulations/hparam/results/togo
