continuous_rate:
  n_alpha: 200
  density_estimation:
    n_bins: 100
    n_knots: 6
    n_features: 10
    degree: 4
continuous_gap:
  n_regressors: 20
  neural_network:
    num_hidden_layers: 1
    num_hidden_units: 256
    lr: 0.005
binary_gap:
  n_regressors: 20
  neural_network:
    num_hidden_layers: 1
    num_hidden_units: 256
    lr: 0.005
binary_rate:
  n_regressors: 20
  neural_network:
    num_hidden_layers: 1
    num_hidden_units: 256
    lr: 0.005


