savedir: /home/selker/eop/eop/run_dry_run/simulations/hparam/results
device: cuda
data:
  ntrain: 6480
  nval: 50000
  ntest: 4574
  outcome: consumption_per_capita_per_day
  weight: hh_wgt
  gt:
    trainpath: /data/eop/malawi/cleaned/train.parquet
    summarypath: /data/eop/malawi/cleaned/summary_2019.parquet
continuous_rate:
  n_alpha: [50, 100, 200]
  density_estimation:
    n_features: [5, 10, 15, 20]
    n_bins: [10, 50, 100, 200] 
    n_knots: [2, 6, 12]
    degree: [2, 4, 6]  

